# Generated by Django 4.2 on 2023-04-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quiz_quiz_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_num",
        ),
    ]
