# Generated by Django 4.2 on 2023-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_question_question_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_num",
            field=models.IntegerField(default=0),
        ),
    ]
