# Generated by Django 4.2 on 2023-04-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_question_question_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="questin_text",
            new_name="question_text",
        ),
    ]
