# Generated by Django 4.2 on 2023-04-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_rename_questin_text_question_question_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="questin_text",
        ),
    ]
